cmake_minimum_required(VERSION 3.22)
project(velyntora_tests LANGUAGES CXX)
enable_testing()
add_subdirectory(../core core-build)
add_executable(canvas_tests canvas_tests.cpp)
target_link_libraries(canvas_tests PRIVATE velyntora_engine)
add_test(NAME canvas_tests COMMAND canvas_tests)
add_executable(layer_tests layer_tests.cpp)
target_link_libraries(layer_tests PRIVATE velyntora_engine)
add_test(NAME layer_tests COMMAND layer_tests)
