cmake_minimum_required(VERSION 3.22.1)
project(velyntora_core LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(velyntora_engine STATIC src/Canvas.cpp src/LayerDocument.cpp src/ProjectIO.cpp src/PixelEffects.cpp src/SelectionTransform.cpp src/ColorAdjustments.cpp src/BlurEffects.cpp)
target_include_directories(velyntora_engine PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
if(ANDROID)
 add_library(velyntora_jni SHARED ../app/src/main/cpp/native_bridge.cpp)
 target_link_libraries(velyntora_jni PRIVATE velyntora_engine log)
endif()
