package art.velyntora.core;
import android.app.AlertDialog;
import android.widget.*;
import android.text.*;
import android.text.InputType;
final class LayerPropertiesDialog {
 static final String[] MODES={"Normal","Multiplicar","Subexponer el color","Sobreexponer el color","Superponer","Diferencia","Aclarar","Oscurecer","Trama","O exclusivo","Luz fuerte","Luz suave","Color","Luminosidad","Tono","Saturación"};
 static AlertDialog show(MainActivity host,int index){
 LinearLayout form=new LinearLayout(host);form.setOrientation(1);form.setPadding(host.dp(20),host.dp(12),host.dp(20),host.dp(12));
 EditText name=new EditText(host);name.setSingleLine(true);name.setText(host.readDrawing().layerName(index));field(host,form,"Nombre:",name);
 CheckBox visible=new CheckBox(host);visible.setText("");visible.setContentDescription("Visible");visible.setChecked(host.readDrawing().layerVisible(index));field(host,form,"Visible:",visible);
 Spinner mode=new Spinner(host);ArrayAdapter<String> adapter=new ArrayAdapter<>(host,android.R.layout.simple_spinner_item,MODES);adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);mode.setAdapter(adapter);mode.setSelection(host.readDrawing().layerBlendMode(index));field(host,form,"Modo de mezcla:",mode);
 LinearLayout row=host.row();EditText number=new EditText(host);number.setSingleLine(true);number.setInputType(InputType.TYPE_CLASS_NUMBER);number.setText(""+Math.round(host.readDrawing().layerOpacity()*100));row.addView(number,new LinearLayout.LayoutParams(host.dp(64),-2));SeekBar slider=new SeekBar(host);slider.setMax(100);slider.setProgress(Math.round(host.readDrawing().layerOpacity()*100));slider.setContentDescription("Opacidad");for(int direction:new int[]{-1,1}){Button step=new Button(host);step.setText(direction<0?"−":"+");step.setMinWidth(0);step.setMinimumWidth(0);step.setPadding(0,0,0,0);step.setContentDescription(direction<0?"Reducir opacidad":"Aumentar opacidad");step.setOnClickListener(v->number.setText(""+Math.max(0,Math.min(100,slider.getProgress()+direction))));row.addView(step,new LinearLayout.LayoutParams(host.dp(36),host.dp(48)));}row.addView(slider,new LinearLayout.LayoutParams(0,host.dp(48),1));field(host,form,"Opacidad:",row);
 slider.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int v,boolean user){if(user)number.setText(""+v);}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});
 number.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){try{int v=Integer.parseInt(s.toString());if(v>=0&&v<=100)slider.setProgress(v);}catch(NumberFormatException e){}}public void afterTextChanged(Editable e){}});
 AlertDialog dialog=new AlertDialog.Builder(host).setTitle("Propiedades de capa").setView(host.scrollForm(form)).setNegativeButton("Cancelar",null).setPositiveButton("Aceptar",null).create();LinearLayout title=host.row();title.setPadding(host.dp(16),host.dp(8),host.dp(8),0);android.widget.TextView heading=host.text("Propiedades de capa");heading.setTextSize(16);heading.setGravity(android.view.Gravity.CENTER);title.addView(heading,new LinearLayout.LayoutParams(0,host.dp(48),1));host.iconButton(title,"Cerrar","cancel",dialog::cancel);dialog.setCustomTitle(title);
 dialog.setOnShowListener(d->{for(int button:new int[]{-1,-2}){Button control=dialog.getButton(button);control.setAllCaps(false);control.setTextColor(0xFFFFFFFF);control.setBackgroundColor(button==-1?0xFF397753:0xFF555555);}dialog.getButton(-1).setOnClickListener(v->{int opacity;try{opacity=Integer.parseInt(number.getText().toString());}catch(NumberFormatException e){number.setError("Usa un valor entre 0 y 100");return;}if(opacity<0||opacity>100){number.setError("Usa un valor entre 0 y 100");return;}if(host.readProjectProgress()!=null)return;if(!host.readDrawing().applyLayerProperties(index,name.getText().toString().trim(),visible.isChecked(),opacity/100f,mode.getSelectedItemPosition())){name.setError("Nombre inválido (máximo 4096 bytes UTF-8)");return;}dialog.dismiss();host.refreshLayerPanel();});});dialog.show();android.graphics.drawable.GradientDrawable background=new android.graphics.drawable.GradientDrawable();background.setColor(0xFF303030);background.setCornerRadius(host.dp(12));dialog.getWindow().setBackgroundDrawable(background);dialog.getWindow().setLayout(Math.min(host.dp(560),host.getResources().getDisplayMetrics().widthPixels-host.dp(32)),-2);return dialog;
 }
 private static void field(MainActivity host,LinearLayout form,String label,android.view.View control){
  boolean wide=host.getResources().getConfiguration().screenWidthDp>=600&&host.getResources().getConfiguration().fontScale<=1.4f;
  android.widget.TextView text=host.text(label);
  LinearLayout row=new LinearLayout(host);row.setOrientation(wide?0:1);row.setGravity(android.view.Gravity.CENTER_VERTICAL);row.setPadding(0,host.dp(4),0,host.dp(4));
  row.addView(text,new LinearLayout.LayoutParams(wide?host.dp(110):-1,-2));row.addView(control,new LinearLayout.LayoutParams(wide?0:-1,-2,wide?1:0));form.addView(row,new LinearLayout.LayoutParams(-1,-2));
 }
}
