// JNI composition unit. Signatures and implementation bodies are preserved.
#include "session/EngineSession.inc"
#include "document/DocumentBridge.inc"
#include "history/HistoryBridge.inc"
#include "drawing/DrawingBridge.inc"
#include "rendering/RenderingBridge.inc"
#include "selection/SelectionBridge.inc"
#include "layers/LayersBridge.inc"
#include "effects/EffectsBridge.inc"
#include "remove_ai/RemoveAiBridge.inc"
